name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Cambia esto a 'master' si tu rama principal se llama así

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '26'
          cache: 'pnpm'

      - name: Instalar dependencias
        run: pnpm install

      - name: Ejecutar Linter
        run: pnpm run lint

      - name: Ejecutar Pruebas Unitarias
        run: pnpm test

  docker-build-push:
    needs: test-and-lint # Solo se ejecuta si el linter y los tests pasan exitosamente
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen a DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/solemne-2-web:latest